name: Deploy CloudFormation

on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write   
  contents: read 
  
env:
  AWS_ACCOUNT_PRD: 3917146425
  AWS_ACCOUNT_NPD: 4228463639

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::787842012624:role/github-master-role
        role-session-name: samplerolesession
        aws-region: ap-southeast-2

    - name: Deploy CloudFormation to main branch
      if: github.ref == 'refs/heads/main'                      # This is not necessary, logic is in deploy.py
      run: |
        python scripts/deploy.py


